apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: systesting
spec:
  params:
    - name: run-id
      type: string
      default: systesting-demo
    - name: init-version
      type: string
      default: v4.0.9
    - name: target-version
      type: string
      default: v5.0.2
  workspaces:
    - name: manifest
  tasks:
    - name: env-prepare
      taskRef:
        name: systesting-prepare-env
      params:
        - name: run-id
          value: "$(params.run-id)"
        - name: init-version
          value: "$(params.init-version)"
      workspaces:
        - name: manifest
          workspace: manifest
    - name: precheck-run
      taskRef:
        name: systesting-precheck-run
      runAfter:
        - env-prepare
      params:
        - name: run-id
          value:
          value: "$(params.run-id)"
        - name: init-version
          value: "$(params.init-version)"
      workspaces:
        - name: manifest
          workspace: manifest
    - name: upgrade
      taskRef:
        name: systesting-upgrade-ops
      runAfter:
        - precheck-run
      params:
        - name: run-id
          value:
          value: "$(params.run-id)"
        - name: target-version
          value: "$(params.target-version)"
      workspaces:
        - name: manifest
          workspace: manifest  
    - name: postcheck-run
      taskRef:
        name: systesting-postcheck-run
      runAfter:
        - upgrade
      params:
        - name: run-id
          value:
          value: "$(params.run-id)"
        - name: target-version
          value: "$(params.target-version)"
      workspaces:
        - name: manifest
          workspace: manifest      
    - name: teardown
      taskRef:
        name: systesting-teardown
      runAfter:
        - postcheck-run
      params:
        - name: run-id
          value: "$(params.run-id)"
