apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: systesting
spec:
  params:
    - name: run-id
      type: string
      default: systesting-demo
    - name: init-version
      type: string
      default: v4.0.9
  workspaces:
    - name: manifest
  tasks:
    # - name: env-prepare
    #   taskRef:
    #     name: systesting-prepare-env
    #   params:
    #     - name: run-id
    #       value: "$(params.run-id)"
    #     - name: init-version
    #       value: "$(params.init-version)"
    #   workspaces:
    #     - name: manifest
    #       workspace: manifest
    - name: workload-run
      taskRef:
        name: systesting-workload-run
      # runAfter:
      #   - env-prepare
      params:
        - name: run-id
          value:
          value: "$(params.run-id)"
      workspaces:
        - name: manifest
          workspace: manifest
    # - name: teardown
    #   taskRef:
    #     name: systesting-teardown
    #   runAfter:
    #     - workload-run
    #   params:
    #     - name: run-id
    #       value: "$(params.run-id)"
