apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: systesting-demo-
spec:
  serviceAccountName: system-testing
  pipelineRef:
    name: systesting
  workspaces:
    - name: manifest
      emptyDir: {}
  params:
    - name: run-id
      value: systesting-demo
    - name: init-version
      value: v3.0.19
    - name: target-version
      value: v5.0.0-nightly
  timeout: "2h"
